# Generated by Django 5.1.5 on 2025-01-30 05:19
from django.contrib.auth.hashers import make_password
from django.db import migrations


def copy_yii_users(apps, schema_editor):
    Yii_User = apps.get_model('account', 'YiiUser')
    VectorUser = apps.get_model('account', 'VectorUser')

    for user in Yii_User.objects.all():
        phone = ''
        if contact := user.contacts.first():
            phone = contact.value
        if user.pk == 1:
            vu = VectorUser.objects.get(pk=1)
            vu.phone = phone
            vu.date_of_birth = user.date_of_birth
            vu.save()
        else:
            vu = VectorUser.objects.create(
                pk=user.pk,
                username=user.username,
                last_name=user.surname,
                first_name=user.firstname,
                patronymic=user.patronymic,
                date_of_birth=user.date_of_birth,
                phone=phone,
                is_staff=True,
            )
            vu.password = make_password('123')
            vu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_yii_users)
    ]
