# Generated by Django 5.0.12 on 2025-02-25 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20250130_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('permission', models.CharField(choices=[('super_user', 'Администратор'), ('role_edit', 'Управление должностями'), ('user_role_permission_edit', 'Управление правами доступа'), ('user_list', 'Пользователи (список)'), ('user_view', 'Пользователи (просмотр)'), ('user_edit', 'Пользователи (изменение)'), ('company_full', 'Компании'), ('employee_list', 'Работники (список)'), ('employee_view', 'Работники (просмотр)'), ('employee_edit', 'Работники (изменение)'), ('employee_rate_edit', 'Работники (зарплата)'), ('employee_credit', 'Кредиты'), ('employee_time_full', 'Рабочее время (полный доступ)'), ('employee_work_item_full', 'Сдельная работа (польный доступ)'), ('project_full', 'Проекты (полный доступ)'), ('project_list', 'Проекты (список)'), ('project_view', 'Проекты (просмотр)'), ('project_edit', 'Проекты (изменение)'), ('partner_edit', 'Партнеры (изменение)'), ('partner_view', 'Партнеры (просмотр)'), ('salary_full', 'Зарплата (полный доступ)'), ('salary_employee_list', 'Зарплата (список работников)'), ('salary_employee_view', 'Зарплата (просмотр по работнику)'), ('salary_employee_self_view', 'Зарплата (просмотр собственной)'), ('salary_type_group_edit', 'Зарплата (управление группировкой по типам)'), ('special_vehicle_edit', 'Спецтехника (изменение)'), ('special_vehicle_type_edit', 'Спецтехника типы (изменение)'), ('special_vehicle_driver_edit', 'Спецтехника водители (изменение)'), ('special_vehicle_order_add', 'Спецтехника заявки (создание)'), ('special_vehicle_order_list', 'Спецтехника заявки (список)'), ('special_vehicle_order_view', 'Спецтехника заявки (просмотр)'), ('special_vehicle_order_execute', 'Спецтехника заявки (выполнение)'), ('special_vehicle_order_comment', 'Спецтехника заявки (комментирование)'), ('special_vehicle_order_changes_view', 'Спецтехника заявки (просмотр изменений)'), ('special_vehicle_order_chat_view', 'Спецтехника заявки (просмотр чата)'), ('special_vehicle_order_chat_participants', 'Спецтехника заявки (участие в чате)'), ('work_full', 'Работы (полный доступ)'), ('work_list', 'Работы (список)'), ('work_view', 'Работы (просмотр)'), ('work_edit', 'Работы (изменение)')], max_length=255, verbose_name='Разрешения')),
                ('entity_based', models.BooleanField(default=False, verbose_name='На основе сущности')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.role')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Разрешение роли',
                'verbose_name_plural': 'Разрешения роли',
                'db_table': 'role_permission',
            },
        ),
        migrations.CreateModel(
            name='UserPermissionEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('entity_class', models.CharField(max_length=255, verbose_name='Класс')),
                ('entity_id', models.IntegerField(verbose_name='Id объекта')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('role_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.rolepermission', verbose_name='Разрешение роли')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сущность разрешения пользователя',
                'verbose_name_plural': 'Сущность разрешения пользователя',
                'db_table': 'user_permission_entity',
            },
        ),
    ]
