# Generated by Django 5.1.5 on 2025-01-30 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('keyword', models.CharField(max_length=64, verbose_name='Слова')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('deleted', 'Удалённый')], default='active', max_length=64, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Событие уведомления',
                'verbose_name_plural': 'События уведомления',
                'db_table': 'notification_event',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('type', models.CharField(choices=[('web', 'Web'), ('push', 'Push'), ('email', 'Email'), ('telegram', 'Telegram')], default='web', max_length=16, verbose_name='Тип')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('deleted', 'Удалённый')], default='active', max_length=64, verbose_name='Статус')),
                ('subject', models.TextField(verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('notification_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationevent', verbose_name='Событие уведомления')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'db_table': 'notification_template',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('read', 'Прочитано'), ('deleted', 'Удалено'), ('blocked', 'Заблокировано'), ('inactive', 'Неактивно')], default='sent', max_length=255, verbose_name='Статус')),
                ('model_class', models.CharField(max_length=255, verbose_name='Класс модели')),
                ('model_id', models.IntegerField(verbose_name='ID модели')),
                ('recipient_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='Получатель')),
                ('sent_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отправитель')),
                ('subject', models.TextField(verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('data', models.JSONField(verbose_name='JSON данные')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='ID Получателя')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='ID Отправителя')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('notification_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificationtemplate', verbose_name='Шаблон уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notification',
            },
        ),
    ]
