# Generated by Django 5.1.5 on 2025-01-30 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('company', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('show_time_column', models.BooleanField(verbose_name='Показывать колонку с окладами/временем')),
                ('show_total_column', models.BooleanField(verbose_name='Показывать колонку Итого')),
            ],
            options={
                'verbose_name': 'Вид отображения таблицы зарплат',
                'verbose_name_plural': 'Виды отображения таблицы зарплат',
                'db_table': 'salary_view',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('role_note', models.CharField(blank=True, max_length=255, verbose_name='Примечания к должности')),
                ('surname', models.CharField(blank=True, max_length=255, verbose_name='Фамилия')),
                ('firstname', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('employment_date', models.DateField(verbose_name='Дата принятия на работу')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('remuneration_to_delete', models.CharField(choices=[('salary', 'Оклад'), ('hourly', 'Почасовая')], default='salary', max_length=64, verbose_name='Вид оплаты труда')),
                ('salary_rate_to_delete', models.FloatField(verbose_name='Ставка')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('fired', 'Уволенный')], default='active', max_length=16, verbose_name='Статус')),
                ('bank_account_number', models.CharField(blank=True, max_length=255, verbose_name='Номер счета')),
                ('bank_bik', models.CharField(blank=True, max_length=255, verbose_name='БИК банка')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='company.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.role', verbose_name='Должность')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('credit_amount', models.FloatField(verbose_name='Сумма кредита')),
                ('credit_date', models.DateField(verbose_name='Дата выдачи')),
                ('percent', models.FloatField(default=0, verbose_name='Процент')),
                ('payments_count', models.IntegerField(verbose_name='Количество платежей')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
                'db_table': 'employee_credit',
            },
        ),
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'employee_group',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employeegroup', verbose_name='Отдел'),
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('salary_rate', models.FloatField(blank=True, null=True, verbose_name='Ставка')),
                ('remuneration_type', models.CharField(choices=[('salary', 'Оклад'), ('hourly', 'Почасовая')], default='salary', max_length=64, verbose_name='Тип')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'db_table': 'employee_salary',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Сотрудник')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Сдельная работа',
                'verbose_name_plural': 'Сдельные работы',
                'db_table': 'employee_work_item',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Месяц')),
                ('date_first_day', models.DateField(verbose_name='')),
                ('date_last_day', models.DateField(verbose_name='')),
                ('work_hours', models.PositiveSmallIntegerField(verbose_name='Рабочих часов')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Заметки')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'verbose_name_plural': 'Зарплата',
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='SalaryEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('salary_rate_to_delete', models.FloatField(verbose_name='Ставка')),
                ('hours_to_delete', models.FloatField(blank=True, null=True, verbose_name='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.salary', verbose_name='Зарплата')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'db_table': 'salary_employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours', models.FloatField(verbose_name='Время')),
                ('ratio', models.FloatField(default=1, verbose_name='Коэффициент')),
                ('type', models.CharField(choices=[('work', 'Рабочее время'), ('leave', 'Административный отпуск'), ('vacation', 'Отпуск'), ('sick', 'Больничный')], default='work', max_length=16, verbose_name='Тип')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='Проект')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('salary_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.salaryemployee', verbose_name='')),
            ],
            options={
                'db_table': 'employee_time',
            },
        ),
        migrations.CreateModel(
            name='SalaryEmployeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.FloatField(verbose_name='Сумма')),
                ('type', models.CharField(choices=[('advance', 'Аванс'), ('salary', 'Зарплата'), ('advance_card', 'Аванс на карту'), ('salary_card', 'Зарплата на карту'), ('cash', 'Выдача наличных'), ('loan_return', 'Возврат кредита'), ('fine', 'Штраф'), ('prev', 'Перенос'), ('hours', 'Начисления'), ('vacation', 'Отпускные'), ('sick', 'Больничные'), ('work', 'Работы'), ('fuel', 'ГСМ'), ('trip', 'Командировочные'), ('loan', 'Зачисление кредита'), ('bonus', 'Премия'), ('dismissal', 'Расчет при увольнении'), ('other', 'Другое')], default='salary_card', max_length=16, verbose_name='Тип')),
                ('type_note', models.CharField(max_length=255, verbose_name='Уточнение типа')),
                ('note', models.TextField(blank=True, default='', verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('salary_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.salaryemployee', verbose_name='')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'db_table': 'salary_employee_item',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('payment_amount', models.FloatField(verbose_name='Сумма платежа')),
                ('paid_amount', models.FloatField(verbose_name='Оплачено')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('employee_credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employeecredit', verbose_name='Кредит')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
                ('salary_employee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.salaryemployeeitem')),
            ],
            options={
                'verbose_name': 'Платёж по кредиту',
                'verbose_name_plural': 'Платежи по кредитам',
                'db_table': 'employee_credit_payment',
            },
        ),
        migrations.AddField(
            model_name='employeecredit',
            name='salary_employee_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.salaryemployeeitem'),
        ),
        migrations.CreateModel(
            name='SalaryEmployeeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('from_date', models.DateField(verbose_name='Дата начала')),
                ('to_date', models.DateField(verbose_name='Дата окончания')),
                ('hours', models.FloatField(verbose_name='Сумма')),
                ('salary_rate', models.FloatField(verbose_name='Ставка')),
                ('remuneration_type', models.CharField(choices=[('salary', 'Оклад'), ('hourly', 'Почасовая')], default='salary', max_length=16, verbose_name='Тип')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('salary_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.salaryemployee', verbose_name='')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'db_table': 'salary_employee_rate',
            },
        ),
        migrations.CreateModel(
            name='SalaryTypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'db_table': 'salary_type_group',
            },
        ),
        migrations.CreateModel(
            name='SalaryTypeGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('type', models.CharField(choices=[('advance', 'Аванс'), ('salary', 'Зарплата'), ('advance_card', 'Аванс на карту'), ('salary_card', 'Зарплата на карту'), ('cash', 'Выдача наличных'), ('loan_return', 'Возврат кредита'), ('fine', 'Штраф'), ('prev', 'Перенос'), ('hours', 'Начисления'), ('vacation', 'Отпускные'), ('sick', 'Больничные'), ('work', 'Работы'), ('fuel', 'ГСМ'), ('trip', 'Командировочные'), ('loan', 'Зачисление кредита'), ('bonus', 'Премия'), ('dismissal', 'Расчет при увольнении'), ('other', 'Другое')], default='salary_card', max_length=16, verbose_name='Тип')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('salary_type_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.salarytypegroup', verbose_name='')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'db_table': 'salary_type_group_item',
            },
        ),
    ]
