# Generated by Django 5.1.5 on 2025-02-14 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkTime',
            fields=[
            ],
            options={
                'verbose_name': 'Учет рабочего времени',
                'verbose_name_plural': 'Учет рабочего времени',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.AlterModelOptions(
            name='salaryemployeeitem',
            options={'verbose_name': 'Начисления/Списания', 'verbose_name_plural': 'Начисления/Списания'},
        ),
        migrations.RenameField(
            model_name='salaryemployeeitem',
            old_name='note',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.ManyToManyField(through='employee.SalaryEmployee', to='employee.salary'),
        ),
        migrations.AddField(
            model_name='employeeworkitem',
            name='salary_employee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.salaryemployeeitem'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employees',
            field=models.ManyToManyField(related_name='salary_employees', through='employee.SalaryEmployee', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='salarytypegroup',
            name='salary_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.salaryview', verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='employeecredit',
            name='salary_employee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.salaryemployeeitem'),
        ),
        migrations.AlterField(
            model_name='employeecreditpayment',
            name='salary_employee_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.salaryemployeeitem'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date_first_day',
            field=models.DateField(verbose_name='Дата первого дня'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date_last_day',
            field=models.DateField(verbose_name='Дата последнего дня'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='notes',
            field=models.TextField(blank=True, db_column='notes', default='', verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='salaryemployee',
            name='salary_rate_to_delete',
            field=models.FloatField(blank=True, null=True, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='salaryemployeeitem',
            name='type_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Уточнение типа'),
        ),
        migrations.AlterField(
            model_name='salaryemployeerate',
            name='salary_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_employee_rate', to='employee.salaryemployee', verbose_name=''),
        ),
    ]
