# Generated by Django 5.1.5 on 2025-02-14 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeworktime_alter_salaryemployeeitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('date_from', models.DateField(verbose_name='Дата перевода')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Сотрудник')),
                ('employee_group_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_group_from', to='employee.employeegroup', verbose_name='Отдел от куда')),
                ('employee_group_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_group_to', to='employee.employeegroup', verbose_name='В какой отдел')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Смена отдела сотрудника',
                'verbose_name_plural': 'смена отдела сотрудника',
                'db_table': 'employee_transfer',
                'ordering': ['employee__surname'],
            },
        ),
    ]
