# Generated by Django 5.1.5 on 2025-02-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeetransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetransfer',
            name='employee_group_from',
        ),
    ]
