# Generated by Django 5.0.12 on 2025-02-25 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employeetransfer_employee_group_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJobTime',
            fields=[
            ],
            options={
                'verbose_name': 'Учет работ',
                'verbose_name_plural': 'Учет работ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employee.employee',),
        ),
        migrations.AlterModelOptions(
            name='employeetime',
            options={'verbose_name': 'Учёт рабочего времени', 'verbose_name_plural': 'Учёт рабочего времени'},
        ),
        migrations.AlterModelOptions(
            name='employeeworktime',
            options={'verbose_name': 'Учет времени', 'verbose_name_plural': 'Учет времени'},
        ),
        migrations.AddField(
            model_name='employeetime',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='employee_group_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_group_from', to='employee.employeegroup', verbose_name='Из какого отдела'),
        ),
        migrations.AlterField(
            model_name='employeetime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_time', to='employee.employee', verbose_name='Сотрудник'),
        ),
    ]
