# Generated by Django 5.1.5 on 2025-01-30 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('inn', models.CharField(blank=True, max_length=255, verbose_name='ИНН')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Юридический адрес')),
                ('basis_title', models.CharField(blank=True, max_length=255, verbose_name='Основание')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Директор')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('status', models.CharField(default='active', max_length=16, verbose_name='Статус')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменено пользователем')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'company',
            },
        ),
    ]
